#!/bin/sh
. lib/msg.sh

andmap() {
	while read -r l; do
		eval [ ! "${l}" ] || return 1
	done <<EOF
"${author}" = "${eauthor}"
"${content}" = "${econtent}"
"${em}" = "${eem}"
"${attach}" = "${eattach}"
EOF
	return 0
}

test() {
	exit=0
	while read -r l; do
		echo $l
		msg_extractmsg "${l}"
	done <<EOF
viz,"somethingsomething,else",[],[]
hahaxd,something else,[],[]
viz,"""test""",[],[]
EOF
	return ${exit}
}

test
