#!/bin/sh
. lib/msg.sh

andmap() {
	while read -r l; do
		eval [ ! "${l}" ] || return 1
	done <<EOF
"${author}" = "${eauthor}"
"${content}" = "${econtent}"
"${em}" = "${eem}"
"${attach}" = "${eattach}"
EOF
	return 0
}

test() {
	exit=0
	while read -r l; do
		eval "${l}"
		eval "$(msg_extractmsg "${l}")"
		andmap || {
			echo ${0##*/}: ${l} failed
			exit=1
		}
	done <<EOF
input="author='viz',content='somethingsomething',em='[]',attach='[]'" \
	eauthor="viz" econtent="somethingsomething" eem=[] eattach=[]
input="author='hahaxd',content='something else',em='[]',attach='[]'" \
	eauthor="hahaxd" econtent="something else" eem="[]" eattach=[]
EOF
	return ${exit}
}

test
