#!/bin/sh

BPREFIX=-
PREFIX=.
_TAGDB=test/data/tagdb
_OWNDB=test/data/tagowndb

for i in "${_TAGDB}" "${_OWNDB}"; do
	rm -r "${i}"; mkdir -p "${i}"
done

. lib/tags.sh

test() {
	while read -r l; do
		tags_parse "${l}" viz
	done <<EOF
-tags set blah blah
-tags get blah
EOF
}

test
