#!/bin/sh
# A discord "bot" using dcfs

read -r TOKEN <data/.token
read -r SERVER <data/.server
read -r CHAN <data/.chan
read -r MNT <data/.mnt
read -r OWNER <data/.owner

BPREFIX='-'

die() {
	fusermount -uz "${MNT}"
}

init() {
	TOKEN="${TOKEN}" dcfs "${MNT}" \
		 author='{{.Author.Username}}' content='{{.Content}}' \
		 em='{{json .Embed}}' attach='{{json .Attachment}}' >data/dcfs.log
}
